spring:
  datasource:
    #    driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@cnl25026014.cn.hsbc:2001/UCN_00001_DCEP.cn.hsbc
    #    url: jdbc:oracle:thin:@10.5.181.30:1521:xe
    #    username: dcwlt_direct_company
    #    password: dcwlt_direct_company
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

server:
  port: 8088


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug